version: '3.9'

services:
  tm-1-5:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=1
      - END_SEED=5
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-6-10:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=6
      - END_SEED=10
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-11-15:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=11
      - END_SEED=15
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-16-20:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=16
      - END_SEED=20
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-21-25:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=21
      - END_SEED=25
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-26-30:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=26
      - END_SEED=30
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-31-35:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=31
      - END_SEED=35
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-36-40:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=36
      - END_SEED=40
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-41-45:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=41
      - END_SEED=45
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-46-50:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=46
      - END_SEED=50
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-51-55:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=51
      - END_SEED=55
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-56-60:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=56
      - END_SEED=60
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-61-65:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=61
      - END_SEED=65
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-66-70:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=66
      - END_SEED=70
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-71-75:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=71
      - END_SEED=75
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-76-80:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=76
      - END_SEED=80
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-81-85:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=81
      - END_SEED=85
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-86-90:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=86
      - END_SEED=90
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-91-95:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=91
      - END_SEED=95
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
  tm-96-100:
    image: quay.io/p-baldini/2025-etm:3.0.0
    environment:
      - WORK_DIR=/home/persistent/2025-etm/tm/E/
      - TASK=tm
      - STRATEGY=E
      - START_SEED=96
      - END_SEED=100
      - ARENA=tmaze.wbt
    volumes:
      - "data:/home/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 131072
    entrypoint: "/home/docker_entrypoint.sh"
volumes:
  data:
    name: paolo.baldini-volume
